// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZki_QLgZeElTTzydsknJjdZ8roGhX6B8',
    appId: '1:609167752988:web:928db92288df5bf30344d9',
    messagingSenderId: '609167752988',
    projectId: 'libapp-1dd5f',
    authDomain: 'libapp-1dd5f.firebaseapp.com',
    storageBucket: 'libapp-1dd5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_oI2LyX5VUTFB4mX8nGTk7Lsv8SkvcE',
    appId: '1:609167752988:android:b218b36b9fc4ccdd0344d9',
    messagingSenderId: '609167752988',
    projectId: 'libapp-1dd5f',
    storageBucket: 'libapp-1dd5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrPhbBCQBJo6rwhmF94DP8YoK1srFDys',
    appId: '1:609167752988:ios:f2829147872df4310344d9',
    messagingSenderId: '609167752988',
    projectId: 'libapp-1dd5f',
    storageBucket: 'libapp-1dd5f.firebasestorage.app',
    iosBundleId: 'com.bima.libraryApp',
  );
}
// merge